### ISSUE TITLE
Conversion of fastText embeddings

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#34]
We could get a lot of additional pretrained embeddings for 'free' if we convert fastText embeddings from:

https://fasttext.cc/docs/en/crawl-vectors.html

Any opinions?

**Comment by danieldk** [comment]
Currently downloading the CC embeddings.

**Comment by NianhengWu** [comment]
Also on it. We can divide work I guess?

**Comment by danieldk** [comment]
Could you do the wikipedia embeddings? I have already downloaded all the common crawl embeddings and they are now uncompressing.

**Comment by NianhengWu** [comment]
Sure, doing it

**Comment by sebpuetz** [comment]
Seems like I'm a bit late to the party. Anyways, I don't see a downside to utilize the pretrained embeddings offered by fastText.

We might want to add some of the convenience methods that fastText offers, such as generating a new embeddings file based on a list of input words. Otherwise going from fastText format to finalfusion loses some functionality (not considering the text classification here). Also, I'd say that's convenient functionality to have anyways. What's your take on that?

**Comment by danieldk** [comment]
It's done converting all the Common Crawl embeddings:

http://www.sfs.uni-tuebingen.de/a3-public-data/finalfusion-fasttext/cc/

The Japanese and Korean embeddings failed because they contained incomplete/invalid UTF-8 sequences. I guess we could read (and thus convert) such embeddings with `String::from_utf8_lossy`. We could consider adding an additional reader of reader flag that permits lossy conversions.

**Comment by sebpuetz** [comment]
> The Japanese and Korean embeddings failed because they contained incomplete/invalid UTF-8 sequences. I guess we could read (and thus convert) such embeddings with `String::from_utf8_lossy`. We could consider adding an additional reader of reader flag that permits lossy conversions.

I also spent a good part of the day fixing messed up encodings in the same batch of embeddings that I was dealing with yesterday. So I'd be in favor of adding such a flag, since there are apparently a bunch of embeddings with borked encodings floating around. The pythonic solution I saw in some programs was using the `surrogateescape` error handler in `open`.

**Comment by danieldk** [comment]
Now the conversion of Japanese and Korean embeddings fail in a different manner: the size of the embedding matrix is not equal to the vocab size + number of buckets. I guess there are more odd things happening here than just the incorrect UTF-8 incoding.

I will postpone further investigation until after my holiday.

**Comment by danieldk** [comment]
At any rate, we should add a README to the embeddings that are already converted and link them from the finalfusion page.

**Comment by danieldk** [comment]
Done. I will close this now, we could make separate issues for the failed embeddings, once we figure out what is wrong with them.
