### ISSUE TITLE
The naming of NGramIndices vs. SubwordIndices traits is confusing

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#80]
Either they are both subwords or n-grams. But the current naming suggests that there is a difference.

**Comment by sebpuetz** [comment]
Rustdocs are outdated, too:

~~~Rust
/// N-gram indexing assigns an identifier to each subword (n-gram) of a
/// string. A subword is indexed by computing its hash and then mapping
/// the hash to a bucket.
///
/// Since a non-perfect hash function is used, multiple subwords can
/// map to the same index.
~~~

**Comment by NianhengWu** [comment]
Indeed. How about:

SubwordIndices --> GetSubwordIndices
NgramIndices --> SubwordIndices

**Comment by danieldk** [comment]
Still doesn't explain the differences, they are almost the same trait, except that one includes the ngrams itself and the other doesn't. And in one has optional indices and the other doesn't?

They should probably be one in the same trait, which has two methods like `subword_indices` and `subword_indices_with_ngrams`. And have one implemented in terms of the other (without the inefficiency of going through another `Vec`).

Another related issue is that we used to use the term *subword* primarily, but now *ngram* has also sneaked in, but they are really the same.

**Comment by sebpuetz** [comment]
To add to this: `subword::SubwordIndices` vs `chunks::vocab::SubwordIndices` shouldn't exist like this either
