### ISSUE TITLE
Question: why don't we have support for computing analogy test accuracy for embeddings with quantized storage?

### ISSUE THREAD

**Issue by NianhengWu** [finalfusion/finalfusion-rust#82]
Hi! This may sound stupid but I have been wondering about this... I tried to reconstruct the whole ```QuantizedArray``` storage into ```NdArray``` storage and wrap it into ```StorageViewWrap``` so that I can compute the accuracy of analogy test, but why don't we have a function for this so we can compute accuracy directly?(Or we do but I fail to find it?)

**Comment by danieldk** [comment]
It's a good question. We rely on fast matrix-vector multiplications to compute the cosine similarities between a given embedding and all other embeddings. Such matrix-vector multiplications are not possible in quantized storage, because the embedding matrix is implicit. So, we'd either have to compute it on the fly (too expensive to do for each query). Or precompute the full embedding matrix once. We could do the latter by providing `From<QuantizedArray> for NdArray` or something along those lines and use that in `compute-accuracy`. But we should be careful with such `From` instances, because someone may put an `into()` or `Into<...>` somewhere without realizing the ramifications.

I think the best solution would be to provide the opposite of the `finalfusion quantize` command (`finalfusion reconstruct`), that would convert a quantized matrix to a normal matrix. It would make the evaluation possible, but no one would accidentally convert a quantized matrix in a non-quantized matrix.

I'll file an issue in `finalfusion-utils` for this command.
